name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      test:
        description: test input
        required: false
        default: hello
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo hello
